dist: xenial
language: python

env:
    global:
        - PATH=$HOME/neovim/bin:$PATH

install:
    - pip install -U covimerage
    - git clone https://github.com/junegunn/vader.vim.git test/vader.vim
    - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"

script:
    - ./run_test.sh

after_success:
    - covimerage xml
    - bash <(curl -s https://codecov.io/bash) -f coverage.xml

notifications:
    email: false
